package android.database;
import android.content.ContentResolver;
import android.net.Uri;
import android.os.Bundle;
import java.io.Closeable;
import java.util.List;

public interface Cursor extends Closeable {
    void close();
    void copyStringToBuffer(int p0, CharArrayBuffer p1);
    byte[] getBlob(int p0);
    int getColumnCount();
    int getColumnIndex(String p0);
    int getColumnIndexOrThrow(String p0);
    String getColumnName(int p0);
    String[] getColumnNames();
    int getCount();
    double getDouble(int p0);
    Bundle getExtras();
    float getFloat(int p0);
    int getInt(int p0);
    long getLong(int p0);
    Uri getNotificationUri();
    int getPosition();
    short getShort(int p0);
    String getString(int p0);
    int getType(int p0);
    boolean getWantsAllOnMoveCalls();
    boolean isAfterLast();
    boolean isBeforeFirst();
    boolean isClosed();
    boolean isFirst();
    boolean isLast();
    boolean isNull(int p0);
    boolean move(int p0);
    boolean moveToFirst();
    boolean moveToLast();
    boolean moveToNext();
    boolean moveToPosition(int p0);
    boolean moveToPrevious();
    void registerContentObserver(ContentObserver p0);
    void registerDataSetObserver(DataSetObserver p0);
    Bundle respond(Bundle p0);
    void setExtras(Bundle p0);
    void setNotificationUri(ContentResolver p0, Uri p1);
    void setNotificationUris(ContentResolver p0, java.util.List<Object> p1);
    void unregisterContentObserver(ContentObserver p0);
    void unregisterDataSetObserver(DataSetObserver p0);
}
