package android.media;

public class ExifInterface {
    public ExifInterface() {}

    public static final int ORIENTATION_FLIP_HORIZONTAL = 0;
    public static final int ORIENTATION_FLIP_VERTICAL = 0;
    public static final int ORIENTATION_NORMAL = 0;
    public static final int ORIENTATION_ROTATE_180 = 0;
    public static final int ORIENTATION_ROTATE_270 = 0;
    public static final int ORIENTATION_ROTATE_90 = 0;
    public static final int ORIENTATION_TRANSPOSE = 0;
    public static final int ORIENTATION_TRANSVERSE = 0;
    public static final int ORIENTATION_UNDEFINED = 0;
    public static final int STREAM_TYPE_EXIF_DATA_ONLY = 0;
    public static final int STREAM_TYPE_FULL_IMAGE_DATA = 0;
    public static final int TAG_APERTURE_VALUE = 0;
    public static final int TAG_ARTIST = 0;
    public static final int TAG_BITS_PER_SAMPLE = 0;
    public static final int TAG_BRIGHTNESS_VALUE = 0;
    public static final int TAG_CFA_PATTERN = 0;
    public static final int TAG_COLOR_SPACE = 0;
    public static final int TAG_COMPONENTS_CONFIGURATION = 0;
    public static final int TAG_COMPRESSED_BITS_PER_PIXEL = 0;
    public static final int TAG_COMPRESSION = 0;
    public static final int TAG_CONTRAST = 0;
    public static final int TAG_COPYRIGHT = 0;
    public static final int TAG_CUSTOM_RENDERED = 0;
    public static final int TAG_DATETIME = 0;
    public static final int TAG_DATETIME_DIGITIZED = 0;
    public static final int TAG_DATETIME_ORIGINAL = 0;
    public static final int TAG_DEFAULT_CROP_SIZE = 0;
    public static final int TAG_DEVICE_SETTING_DESCRIPTION = 0;
    public static final int TAG_DIGITAL_ZOOM_RATIO = 0;
    public static final int TAG_DNG_VERSION = 0;
    public static final int TAG_EXIF_VERSION = 0;
    public static final int TAG_EXPOSURE_BIAS_VALUE = 0;
    public static final int TAG_EXPOSURE_INDEX = 0;
    public static final int TAG_EXPOSURE_MODE = 0;
    public static final int TAG_EXPOSURE_PROGRAM = 0;
    public static final int TAG_EXPOSURE_TIME = 0;
    public static final int TAG_FILE_SOURCE = 0;
    public static final int TAG_FLASH = 0;
    public static final int TAG_FLASHPIX_VERSION = 0;
    public static final int TAG_FLASH_ENERGY = 0;
    public static final int TAG_FOCAL_LENGTH = 0;
    public static final int TAG_FOCAL_LENGTH_IN_35MM_FILM = 0;
    public static final int TAG_FOCAL_PLANE_RESOLUTION_UNIT = 0;
    public static final int TAG_FOCAL_PLANE_X_RESOLUTION = 0;
    public static final int TAG_FOCAL_PLANE_Y_RESOLUTION = 0;
    public static final int TAG_F_NUMBER = 0;
    public static final int TAG_GAIN_CONTROL = 0;
    public static final int TAG_GPS_ALTITUDE = 0;
    public static final int TAG_GPS_ALTITUDE_REF = 0;
    public static final int TAG_GPS_AREA_INFORMATION = 0;
    public static final int TAG_GPS_DATESTAMP = 0;
    public static final int TAG_GPS_DEST_BEARING = 0;
    public static final int TAG_GPS_DEST_BEARING_REF = 0;
    public static final int TAG_GPS_DEST_DISTANCE = 0;
    public static final int TAG_GPS_DEST_DISTANCE_REF = 0;
    public static final int TAG_GPS_DEST_LATITUDE = 0;
    public static final int TAG_GPS_DEST_LATITUDE_REF = 0;
    public static final int TAG_GPS_DEST_LONGITUDE = 0;
    public static final int TAG_GPS_DEST_LONGITUDE_REF = 0;
    public static final int TAG_GPS_DIFFERENTIAL = 0;
    public static final int TAG_GPS_DOP = 0;
    public static final int TAG_GPS_IMG_DIRECTION = 0;
    public static final int TAG_GPS_IMG_DIRECTION_REF = 0;
    public static final int TAG_GPS_LATITUDE = 0;
    public static final int TAG_GPS_LATITUDE_REF = 0;
    public static final int TAG_GPS_LONGITUDE = 0;
    public static final int TAG_GPS_LONGITUDE_REF = 0;
    public static final int TAG_GPS_MAP_DATUM = 0;
    public static final int TAG_GPS_MEASURE_MODE = 0;
    public static final int TAG_GPS_PROCESSING_METHOD = 0;
    public static final int TAG_GPS_SATELLITES = 0;
    public static final int TAG_GPS_SPEED = 0;
    public static final int TAG_GPS_SPEED_REF = 0;
    public static final int TAG_GPS_STATUS = 0;
    public static final int TAG_GPS_TIMESTAMP = 0;
    public static final int TAG_GPS_TRACK = 0;
    public static final int TAG_GPS_TRACK_REF = 0;
    public static final int TAG_GPS_VERSION_ID = 0;
    public static final int TAG_IMAGE_DESCRIPTION = 0;
    public static final int TAG_IMAGE_LENGTH = 0;
    public static final int TAG_IMAGE_UNIQUE_ID = 0;
    public static final int TAG_IMAGE_WIDTH = 0;
    public static final int TAG_INTEROPERABILITY_INDEX = 0;
    public static final int TAG_ISO_SPEED_RATINGS = 0;
    public static final int TAG_JPEG_INTERCHANGE_FORMAT = 0;
    public static final int TAG_JPEG_INTERCHANGE_FORMAT_LENGTH = 0;
    public static final int TAG_LIGHT_SOURCE = 0;
    public static final int TAG_MAKE = 0;
    public static final int TAG_MAKER_NOTE = 0;
    public static final int TAG_MAX_APERTURE_VALUE = 0;
    public static final int TAG_METERING_MODE = 0;
    public static final int TAG_MODEL = 0;
    public static final int TAG_NEW_SUBFILE_TYPE = 0;
    public static final int TAG_OECF = 0;
    public static final int TAG_OFFSET_TIME = 0;
    public static final int TAG_OFFSET_TIME_DIGITIZED = 0;
    public static final int TAG_OFFSET_TIME_ORIGINAL = 0;
    public static final int TAG_ORF_ASPECT_FRAME = 0;
    public static final int TAG_ORF_PREVIEW_IMAGE_LENGTH = 0;
    public static final int TAG_ORF_PREVIEW_IMAGE_START = 0;
    public static final int TAG_ORF_THUMBNAIL_IMAGE = 0;
    public static final int TAG_ORIENTATION = 0;
    public static final int TAG_PHOTOMETRIC_INTERPRETATION = 0;
    public static final int TAG_PIXEL_X_DIMENSION = 0;
    public static final int TAG_PIXEL_Y_DIMENSION = 0;
    public static final int TAG_PLANAR_CONFIGURATION = 0;
    public static final int TAG_PRIMARY_CHROMATICITIES = 0;
    public static final int TAG_REFERENCE_BLACK_WHITE = 0;
    public static final int TAG_RELATED_SOUND_FILE = 0;
    public static final int TAG_RESOLUTION_UNIT = 0;
    public static final int TAG_ROWS_PER_STRIP = 0;
    public static final int TAG_RW2_ISO = 0;
    public static final int TAG_RW2_JPG_FROM_RAW = 0;
    public static final int TAG_RW2_SENSOR_BOTTOM_BORDER = 0;
    public static final int TAG_RW2_SENSOR_LEFT_BORDER = 0;
    public static final int TAG_RW2_SENSOR_RIGHT_BORDER = 0;
    public static final int TAG_RW2_SENSOR_TOP_BORDER = 0;
    public static final int TAG_SAMPLES_PER_PIXEL = 0;
    public static final int TAG_SATURATION = 0;
    public static final int TAG_SCENE_CAPTURE_TYPE = 0;
    public static final int TAG_SCENE_TYPE = 0;
    public static final int TAG_SENSING_METHOD = 0;
    public static final int TAG_SHARPNESS = 0;
    public static final int TAG_SHUTTER_SPEED_VALUE = 0;
    public static final int TAG_SOFTWARE = 0;
    public static final int TAG_SPATIAL_FREQUENCY_RESPONSE = 0;
    public static final int TAG_SPECTRAL_SENSITIVITY = 0;
    public static final int TAG_STRIP_BYTE_COUNTS = 0;
    public static final int TAG_STRIP_OFFSETS = 0;
    public static final int TAG_SUBFILE_TYPE = 0;
    public static final int TAG_SUBJECT_AREA = 0;
    public static final int TAG_SUBJECT_DISTANCE = 0;
    public static final int TAG_SUBJECT_DISTANCE_RANGE = 0;
    public static final int TAG_SUBJECT_LOCATION = 0;
    public static final int TAG_SUBSEC_TIME = 0;
    public static final int TAG_SUBSEC_TIME_DIGITIZED = 0;
    public static final int TAG_SUBSEC_TIME_ORIGINAL = 0;
    public static final int TAG_THUMBNAIL_IMAGE_LENGTH = 0;
    public static final int TAG_THUMBNAIL_IMAGE_WIDTH = 0;
    public static final int TAG_THUMBNAIL_ORIENTATION = 0;
    public static final int TAG_TRANSFER_FUNCTION = 0;
    public static final int TAG_USER_COMMENT = 0;
    public static final int TAG_WHITE_BALANCE = 0;
    public static final int TAG_WHITE_POINT = 0;
    public static final int TAG_XMP = 0;
    public static final int TAG_X_RESOLUTION = 0;
    public static final int TAG_Y_CB_CR_COEFFICIENTS = 0;
    public static final int TAG_Y_CB_CR_POSITIONING = 0;
    public static final int TAG_Y_CB_CR_SUB_SAMPLING = 0;
    public static final int TAG_Y_RESOLUTION = 0;
    public static final int WHITEBALANCE_AUTO = 0;
    public static final int WHITEBALANCE_MANUAL = 0;
    public double getAltitude(Object p0) { return 0.0; }
    public double getAttributeDouble(Object p0, Object p1) { return 0.0; }
    public int getAttributeInt(Object p0, Object p1) { return 0; }
    public boolean getLatLong(Object p0) { return false; }
    public byte getThumbnail() { return 0; }
    public Object getThumbnailBitmap() { return null; }
    public byte getThumbnailBytes() { return 0; }
    public boolean hasAttribute(Object p0) { return false; }
    public boolean hasThumbnail() { return false; }
    public static boolean isSupportedMimeType(Object p0) { return false; }
    public boolean isThumbnailCompressed() { return false; }
    public void saveAttributes() {}
    public void setAttribute(Object p0, Object p1) {}
}
